[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=candy-icons
standard_dialogs=default
style=kvantum-dark

[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,400,0,0,0,0,0"
general="Noto Sans,11,-1,5,400,0,0,0,0,0"
